USE [master]
GO
/****** Object:  Database [MHefny_Task]    Script Date: 14/11/2020 11:38:20 ******/
CREATE DATABASE [MHefny_Task]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MHefny_Task', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.ENTERPRISE\MSSQL\DATA\MHefny_Task.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'MHefny_Task_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.ENTERPRISE\MSSQL\DATA\MHefny_Task_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [MHefny_Task] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MHefny_Task].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MHefny_Task] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MHefny_Task] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MHefny_Task] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MHefny_Task] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MHefny_Task] SET ARITHABORT OFF 
GO
ALTER DATABASE [MHefny_Task] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MHefny_Task] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MHefny_Task] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MHefny_Task] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MHefny_Task] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MHefny_Task] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MHefny_Task] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MHefny_Task] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MHefny_Task] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MHefny_Task] SET  DISABLE_BROKER 
GO
ALTER DATABASE [MHefny_Task] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MHefny_Task] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MHefny_Task] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MHefny_Task] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MHefny_Task] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MHefny_Task] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MHefny_Task] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MHefny_Task] SET RECOVERY FULL 
GO
ALTER DATABASE [MHefny_Task] SET  MULTI_USER 
GO
ALTER DATABASE [MHefny_Task] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MHefny_Task] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MHefny_Task] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MHefny_Task] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [MHefny_Task] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'MHefny_Task', N'ON'
GO
USE [MHefny_Task]
GO
/****** Object:  Table [dbo].[User]    Script Date: 14/11/2020 11:38:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FName] [nvarchar](max) NULL,
	[LName] [nvarchar](max) NULL,
	[Username] [nvarchar](max) NULL,
	[Password] [nvarchar](max) NULL,
	[Email] [nvarchar](max) NULL,
	[Phone] [nvarchar](max) NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
USE [master]
GO
ALTER DATABASE [MHefny_Task] SET  READ_WRITE 
GO
